Add instructions for dumping .code and building patches (Fix: #16)
zaksabeast/DreamRadarCartRedirect pull request #17
Opened 2023-08-02 17:53 UTC by alvv-z

I hope this is satisfactory. If not, please let me know and I will edit accordingly.

2023-08-04 02:19 UTC, zaksabeast requested changes
This is great, thank you!  The attention to detail is fantastic, and it was easy to read through.

I have a few tiny requests, mostly just personal preference, but otherwise this looks good.

2023-08-04 02:19 UTC, zaksabeast commented on README.md
> +- [ ] The respective title (Dream Radar or Transporter) installed on your 3DS
Let's use a regular bullet throughout the document.  A checkbox is a good choice, but my personal preference is a bullet since the user won't be able to check the box.

2023-08-04 02:19 UTC, zaksabeast commented on README.md
> +11. Select `Copy to 0:/gm9/out` and press <kbd>A</kbd>
Let's remove 'and press A' for any lines that end with it.  'Select <option>' should be clear and implies pressing 'A'.

2023-08-04 02:19 UTC, zaksabeast commented on README.md
> +   2. Open a shell in the folder containing your recently renamed `.bin`and the rest of the above resources. If you are using installed versions of the aforementioned tools, omit the preceding `./`.
I think we can make these sections slightly more succinct:
```
Open a shell in the folder containing the renamed `.bin` file and other resources. If you're using installed versions of the tools, omit the preceding `./`.
```

2023-08-04 02:19 UTC, zaksabeast commented on README.md
> +### Building the patches yourself
It seems like this line should be the parent of the following guides, however this and the guides are each `h3`, and `h4` feels a bit too small/nested for the following guides.

Let's remove this "Building the patches yourself" line and use "Build Patch for Dream Radar (All regions)", "Build Patch for Dream Radar (Japan)", and "Build Patch for Transporter" for the guides beneath here.  That will allow each guide to be `h3` without losing any context.

2023-08-07 13:04 UTC, alvv-z commented
> This is great, thank you! The attention to detail is fantastic, and it was easy to read through.
> 
> I have a few tiny requests, mostly just personal preference, but otherwise this looks good.
I have added your suggested changes. Please let me know if there is anything else.

2023-08-09 23:41 UTC, zaksabeast approved these changes
This is awesome, I really appreciate it.  Thank you again!

2023-08-09 23:41 UTC, merged